name: "Auto NotPix"

on:
  schedule:
    - cron: "0 0 * 1 *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Copy file from another location
        run: |
          cp sessionsMain/Krutkij.session sessions/Krutkij.session
          cp sessionsMain/Orange.session sessions/Orange.session
          cp sessionsMain/Toxxa.session sessions/Toxxa.session
          cp sessionsMain/accounts.json sessions/accounts.json
          cp bot/config/configLongTime.py bot/config/config.py 
          cp -f MainOriginal.py main.py
          ls sessions/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./main.py -a 1
          timeout-minutes: 580
