name: "Auto NotPix2"

on:
  schedule:
    - cron: "5, 4-11 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Replace a file
        run: |
          echo "[
  {
    "session_name": "name_example",
    "user_agent": "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36",
    "proxy": "socks5://72.195.114.169:4145"
  },
  {
    "session_name": "HeyahFox",
    "user_agent": "Mozilla/5.0 (Linux; Android 11.0; Pixel 3 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.2.8486.59 Mobile Safari/537.36",
    "proxy": null
  },
  {
    "session_name": "Orange",
    "user_agent": "Mozilla/5.0 (Linux; Android 12.0; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.2.7784.70 Mobile Safari/537.36",
    "proxy": null
  }]" > sessiobs/accounts.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./main.py -a 1
          
